services:
  - type: web
    name: recicash-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        sync: false
      - key: PORT
        value: 10000
      - key: HOST_API
        fromService:
          name: recicash-api
          type: web
          property: url
          append: /api
      - key: JWT_SECRET
        sync: false
    autoDeploy: true